import { Inter } from 'next/font/google'
import '../components/global-styles/best.scss';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Hi, I'm Andrei.",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
